# Generated by Django 4.1.2 on 2023-09-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='List_Opps_volon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title5', models.CharField(max_length=40)),
                ('description5', models.CharField(max_length=2000)),
                ('short_des5', models.CharField(max_length=2000)),
                ('url_opp5', models.CharField(max_length=5000)),
                ('img5', models.ImageField(blank=True, null=True, upload_to='imagesopps')),
                ('category5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category5', to='club.category')),
            ],
        ),
        migrations.CreateModel(
            name='List_Opps_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title4', models.CharField(max_length=40)),
                ('description4', models.CharField(max_length=2000)),
                ('short_des4', models.CharField(max_length=2000)),
                ('url_opp4', models.CharField(max_length=5000)),
                ('img4', models.ImageField(blank=True, null=True, upload_to='imagesopps')),
                ('category4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category4', to='club.category')),
            ],
        ),
        migrations.CreateModel(
            name='List_Opps_others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title6', models.CharField(max_length=40)),
                ('description6', models.CharField(max_length=2000)),
                ('short_des6', models.CharField(max_length=2000)),
                ('url_opp6', models.CharField(max_length=5000)),
                ('img6', models.ImageField(blank=True, null=True, upload_to='imagesopps')),
                ('category6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category6', to='club.category')),
            ],
        ),
        migrations.CreateModel(
            name='List_Opps_intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title3', models.CharField(max_length=40)),
                ('description3', models.CharField(max_length=2000)),
                ('short_des3', models.CharField(max_length=2000)),
                ('url_opp3', models.CharField(max_length=5000)),
                ('img3', models.ImageField(blank=True, null=True, upload_to='imagesopps')),
                ('category3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category3', to='club.category')),
            ],
        ),
        migrations.CreateModel(
            name='List_Opps_des',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(max_length=40)),
                ('description2', models.CharField(max_length=2000)),
                ('description2_1', models.CharField(max_length=2000)),
                ('description2_2', models.CharField(max_length=2000)),
                ('url_opp2', models.CharField(max_length=5000)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='imagesopps')),
                ('category2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='club.category')),
            ],
        ),
        migrations.CreateModel(
            name='List_Opps_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=40)),
                ('description1', models.CharField(max_length=2000)),
                ('short_des1', models.CharField(max_length=2000)),
                ('url_opp1', models.CharField(max_length=5000)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='imagesopps')),
                ('category1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category1', to='club.category')),
            ],
        ),
        migrations.CreateModel(
            name='List_Opps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=2000)),
                ('url_opp', models.CharField(max_length=5000)),
                ('time', models.CharField(max_length=50)),
                ('card_des', models.CharField(max_length=60)),
                ('img', models.ImageField(blank=True, null=True, upload_to='imagesopps')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='club.category')),
            ],
        ),
    ]
