# Generated by Django 4.1.2 on 2023-09-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_opps_course',
            name='time1',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
