# Generated by Django 4.1.2 on 2023-09-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_list_opps_course_time1'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_opps_des',
            name='time22',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list_opps_intern',
            name='time3',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list_opps_others',
            name='time6',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list_opps_program',
            name='time4',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list_opps_volon',
            name='time5',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
